### ISSUE TITLE
Need new methods MongoClientMediator.getRecord, getRecordsInRangeInclusive

### ISSUE THREAD

**Issue by pm8008** [DHSTTOS/implementation#45]
1) Need new method MongoClientMediator.getRecord(String collection, String key, String value)
that returns an array with records whose <key> entry matches <value>.
If there's only one matching record (which e.g. should always be the case for key=="Timestamp"), return an array of length 1.

2) getRecordsInRange: maybe we should have two methods, one which compares
start <= key < end
and one (getRecordsInRangeInclusive) which compares start <= key <= end

**Comment by mgonzalez01** [comment]
1. the current getRecordsInRange returns star <= x < end
the operators in Mongo are 

gte = greater than | equal
gt = greater than 
lte = less than | equal
lt = less than 

implementing any of these is trivial. please let me know which one is more convinient.

**Comment by pm8008** [comment]
The first one please, i.e. exact match. Maybe name it getRecordsWithValue or so.
I now think we don't need the second one. Thanks!

**Comment by pm8008** [comment]
Sorry, but I'd like to ask for another method which goes by record indices:
getRecordsInIndexRange(collectionName, startIndex, endIndex)
where e.g. ("lemgo", 0, 1000) returns the first 1000 records and ("lemgo", 1000, 2000) returns the next 1000 (i.e. from record number 1000 to record number 1999).
(startIndex is inclusive, endIndex is exclusive)
Reason for that is that we don't know how many records there are per second, i.e. if the client request records in a given timespan it might get back too many to handle.

**Comment by mgonzalez01** [comment]
setting the key to _id should do the trick

**Comment by mgonzalez01** [comment]
new function getRecord(colleciton,key,equals) added with the functionality, comment above now applies.
