### ISSUE TITLE
Debug real WebSocket

### ISSUE THREAD

**Issue by hexrcs** [DHSTTOS/implementation#53]

**Comment by hexrcs** [comment]
@pm8008  I think I finally understood the reason why it kept failing on my side, because with `loginToken()` we need that token already in record on the server, right? If we don't run `login()` first to get the token then `loginToken` would be useless.

Can we simplify/modify the code/behavior a bit so it's more clear? (took me 2 hours to realize this 😂)

The `onopen` listener should *not* call `loginToken()` every time, instead there should be checks to see if we need `loginToken()` or `loginAccount()` (which is currently named just `login()`). Since we are basically writing 2 apps that use `wsutils` (login and main page), let's best keep everything modular.

For our convenience, since most of the work needs to be done on the main page, I suggest hardcoding a `loginAccount()` sequence to simulate the events that happened before navigating to main page. So inside the topmost `src/index.js`, let's make a first connection - gets token via "suitcase:12345" and closes, then a second connection - the big game. Later we just need to move the `loginAccount()` into the login page, and use `loginToken()` only on main page.

Actually `loginViaToken` and `loginViaAccount` look better to me.

Another thing is that I am confused about the logic inside `handleSession()`. If the user is logged in already, I don't quite understand the handling there. We are doing a logout here, is that correct? If that's the case, then let's don't use `FAIL` to signal a successful logout, but have a payload for each `SESSION` type/cmd message. (I'm not sure what the param is for here so I used that) Say:

```
cmd: "SESSION"
id: 1
par: "LOGOUT"
status: "OK"

====

cmd: "SESSION"
id: 1
par: "LOGOUT"
status: "FAIL"

====

cmd: "SESSION"
id: 1
par: "LOGIN"
status: "OK"

====

cmd: "SESSION"
id: 1
par: "LOGIN"
status: "FAIL"
```

... And throw an error when the messages don't look like any of these.

Personally this looks cleaner than trying to interpret what the SESSION `FAIL` or `OK` means by referencing a local variable `wsLoggedIn`.

Let me know. 😃

**Comment by hexrcs** [comment]
@pm8008  Maybe have a third pair of session messages so that we can separate login via account and via token. Maybe "login" is not an accurate word for token, authentication perhaps? 😂

**Comment by pm8008** [comment]
Correct analysis :).
1) Yeah, renaming login->loginViaAccount and loginToken->loginViaToken or authenticateViaToken makes sense.
2) Agreed on hardcoding the sequence in src/index.js for the testing phase.

3) I'll comment on handleSession separately in 20 min. or so

3) I'm not clear yet on what you want to use the third pair of session messages for.
Do you want to send two different LOGIN commands, depending on whether you want a token back or not? Or what would be the third pair for?

**Comment by hexrcs** [comment]
@pm8008 By 3 pairs of responses I meant one for each "LOGOUT", "LOGIN" <sub>(via `usr:pwd`)</sub>, "AUTH" <sub>(via `usr:token`, or token only)</sub>.

Because "LOGOUT" is an action of its own, not a failed login when attempted to login when the user is already logged in.

**Comment by hexrcs** [comment]
Basically to make states as explicit as possible, because it would be much easier for maintainers to reason with the code (no need to run the "state machine" in brain).

**Comment by pm8008** [comment]
handleSession: sorry I had forgotten to commit a bug fix, did that right now: on first login we need to store the token.
https://github.com/DHSTTOS/implementation/commit/e429d8101f3b754c9613ccb8a9ff9b3ba4fef773#diff-e4672326032275a493b1c72e3b668527

Receiving SESSION status FAIL in handleMessage means that there is no session/connection, i.e we are not logged in. Doesn't matter if before the arrival of this message we were logged in or not.

I think handleSession should work right now, we can refactor this later.

**Comment by hexrcs** [comment]
Closing the issue as the debugging is done 😅
