### ISSUE TITLE
Find out and mark all deprecated functions in `wsutils.js` and co

### ISSUE THREAD

**Issue by hexrcs** [DHSTTOS/implementation#87]
I have marked the old generic get data one, however this file still needs cleaning up. @pm8008 Could you help with me on this? Just mark them with `@deprecated` in JSdoc or add a comment when you encounter one. 

Thanks.

**Comment by pm8008** [comment]
Will do. I also think that we could move all those function that send a request into another file (wsSendRequests.js or so) and leave only the socket event handlers an their helper functions in wsutils.js

**Comment by mgonzalez01** [comment]
what can I do?
