### ISSUE TITLE
Performance issue when updating selection

### ISSUE THREAD

**Issue by hexrcs** [DHSTTOS/implementation#90]
@pm8008 

Playing with #89 and it looks great. However diagram rendering performs rather poor when we update our selection. :(

I'm looking into how to optimize diagram rendering. In the meantime, could you try to batch the actions of setting the currently selected range in dataStore? For example, only update the selected range in dataStore when mouse click is over, or when the selection doesn't change after a few ms with `setTimeout`? This way we don't need to fire 1000 updates within 1 second to the diagram, or an equal amount of requests to the server later when we lazy pull the data?

**Comment by pm8008** [comment]
Yeah, the performance/interactivity definitely needs improvement.
I'm on it.

**Comment by pm8008** [comment]
I've added 2 checkboxes for the brush, one of which disables smooth/continuous updates (i.e. now only updates when the brush stops moving.)

But I can't get the positioning/alignment for that container right, there's too much space wasted between the copyright and the checkboxes. Could you please take a look? Thanks!
https://github.com/DHSTTOS/implementation/tree/p_brush_config

**Comment by hexrcs** [comment]
For the checkboxes see #91 . In the future if you make a PR I can review inline and add suggestions etc.

**Comment by hexrcs** [comment]
Closing as we disabled continuous updates by default, and now offer the user to re-enable `Smooth scroll` with the checkbox (which ironically lags in most cases, rendering the interaction less smooth 🤣 ).

**Comment by pm8008** [comment]
ResponsiveScatterPlotCanvas is fast enough for smooth scrolling:
7a9b9af6df759856b4925dcd17153fd003916ed0
Is there a reason to not use this instead of the svg variant?

**Comment by hexrcs** [comment]
The commit you pointed to doesn't seem to work when I tried to test. This is the console on init:

![image](https://user-images.githubusercontent.com/26751752/52979483-1b90c080-33d6-11e9-83e9-1e40d79c6576.png)

Using canvas is a good idea. I used the SVG variant because initially I wanted to make the diagrams responsive, and when changing diagram sizes, the resizing animation of the SVG one was smoother than the canvas one (at least it was the case when I was testing).

We can try the canvas version. Also we don't need "responsive" diagrams anymore, so `ScatterPlotCanvas` should do.

I'm not sure if this still allows custom tooltips. Looking into the type def of `ScatterPlotCanvas` reveals that it uses the same props as `ScatterPlot`, so if it's not a stub/bug then it should work. I'm not sure because the tooltips are defined with JSX (React) syntax, and I haven't looked into how the canvas rendering of Nivo is implemented - if they render things to DOM first then draw them onto canvas, that's a no brainer; if that's not true (very likely because the canvas version is supposed to be faster), maybe custom tooltips won't work. Need to experiment with it.

**Comment by hexrcs** [comment]
LOL smart, the tooltips are not rendered to canvas, they are just plain DOM elements floating above the canvas. Then yes, let's use canvas. Thanks for the idea!

**Comment by hexrcs** [comment]
Discussion of converting to canvas (it there's still any) will continue under #93 .

**Comment by pm8008** [comment]
Re. the resizing animation: the nivo doc for the ...Canvas components says "however you'll lose the isomorphic ability and transitions." so yeah, in that regard the svg variant looks better.

Re. testing: The initialization of the brush is buggy. For the time being, try this: select a data source, then click/draw a brush on the lower axis and move it a bit, then the same for the upper axis, and then add the diagram.

**Comment by hexrcs** [comment]
Thanks, but the brush used to work? 🤨

**Comment by hexrcs** [comment]
Got it to work. Cool stuff, canvas is way smoother.

**Comment by pm8008** [comment]
> Thanks, but the brush used to work? 🤨
Yeah,  I'm afraid its a regression caused by changing to the 2-stage-brush setup. :-/
